jobs:
    - job: UnitTests

      strategy:
          matrix:
              Node18:
                  NODE_VERSION: "18.x"
              Node20:
                  NODE_VERSION: "20.x"

      steps:
          - task: NodeTool@0
            inputs:
                versionSpec: $(NODE_VERSION)
            displayName: "Install Node dependencies"
          - script: npm ci
            displayName: "npm ci"
          - script: npm run test
            displayName: "npm build and test"
          - script: npm run test:nolint
            displayName: "npm build and test (no linting)"
          - script: npm run build
            displayName: "npm run build"
          - script: npm pack
            displayName: "npm pack"
          - script: mv durable-functions-*.tgz package.tgz
            displayName: "Rename package file"
          - task: CopyFiles@2
            displayName: "Create smoke test app"
            inputs:
                SourceFolder: "$(System.DefaultWorkingDirectory)/test/test-app"
                Contents: "**"
                TargetFolder: "$(Agent.BuildDirectory)/test-app"
                CleanTargetFolder: true
          - script: npm install $(System.DefaultWorkingDirectory)/package.tgz
            displayName: "Install packed durable-functions module (test app)"
            workingDirectory: $(Agent.BuildDirectory)/test-app
          - script: npm install
            displayName: "npm install (test app)"
            workingDirectory: $(Agent.BuildDirectory)/test-app
          - script: npm run build
            displayName: "Build smoke test app"
            workingDirectory: "$(Agent.BuildDirectory)/test-app"
