trigger:
    branches:
        include:
            - v3.x
    batch: true

pr:
    branches:
        include:
            - v3.x

resources:
    repositories:
        - repository: 1esPipelines
          type: git
          name: 1ESPipelineTemplates/1ESPipelineTemplates
          ref: refs/tags/release

extends:
    template: v1/1ES.Unofficial.PipelineTemplate.yml@1esPipelines
    parameters:
        pool:
            name: 1es-pool-azfunc-public
            image: 1es-windows-2022
            os: windows

        stages:
            - stage: WindowsUnitTests
              dependsOn: []
              jobs:
                  - template: /azure-pipelines/templates/test.yml@self

            - stage: LinuxUnitTests
              dependsOn: []
              jobs:
                  - template: /azure-pipelines/templates/test.yml@self
              pool:
                  name: 1es-pool-azfunc-public
                  image: 1es-ubuntu-22.04
                  os: linux

            - stage: Build
              dependsOn: []
              jobs:
                  - template: /azure-pipelines/templates/build.yml@self
